media:
  input: public/images   # Where uploaded images are saved in your repo
  output: /images        # Public URL path for images in Next.js

content:
  - name: pages
    label: Pages
    type: collection     # Even for single files, we use a collection for organization
    path: content        # Folder containing your Markdown files
    view:
      fields: [title, date]  # Columns shown in the list view (optional but nice)
    files:
      - name: cats
        label: Cats Page
        path: cats.md      # Relative to the collection path (content/cats.md)
        fields:
          - name: title
            label: Title
            type: string
          - name: date
            label: Date
            type: date
          - name: cats
            label: Famous Cats
            type: list
            fields:
              - name: name
                label: Name
                type: string
              - name: description
                label: Description
                type: text
          - name: body
            label: Body Content
            type: rich-text    # For the main Markdown body below the frontmatter