# pages.config.yml (in repo root)
name: "Sunday Bible Study"
version: "1.0"
projectId: your-project-id # Auto-filled after Step 1; check dashboard
collections:
  - name: pages
    label: Pages
    folder: content # Your MD files path
    slugify:
      pathname: "{title}"
      mode: "slug"
    format: "mdx" # Or "md" for plain Markdown
    fields:
      - label: Title
        name: title
        type: "text"
        required: true
      - label: Date
        name: date
        type: "date"
      - label: Author
        name: author
        type: "text"
      - label: Cover Image
        name: coverImage
        type: "image"
        media:
          default: "default-media" # Define media below
      - label: Body
        name: body
        type: "rich-text"
        required: true
media:
  - id: "default-media"
    name: "Default Media"
    folder: "public/assets/blog" # Your images path (relative to repo root)
    rules:
      - minWidth: 300
        maxWidth: 2000
        format: "webp"
        quality: 85
