media: public/assets
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    fields:
      - { name: title, label: Title, type: string }
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
